name: e2e

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Setup Volta
        uses: volta-cli/action@v4.2.1
      - name: Install dependencies
        run: npm ci
      - name: Build test binary
        run: clang ./tests/fixtures/demo.c -o ./tests/fixtures/demo
      - name: Run tests
        run: npm run test
      # TODO: create/use a GitHub Action to parse node:test coverage report and post as comment
