name: e2e

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Volta
        uses: volta-cli/action@v4.2.1
      - name: Node.js version
        run: node -v
      - name: npm version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      # TODO: create/use a GitHub Action to parse node:test coverage report and post as comment
